package com.uniandes.clientes.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;

@DynamoDBTable(tableName = "clients")
public class ClientModel {

        private String id;
        private String name;
        private int cedula;
        private String phone;
        private String email;

        public ClientModel(String name, int cedula, String phone, String email) {
            this.name = name;
            this.cedula = cedula;
            this.phone = phone;
            this.email = email;
        }

    public ClientModel() {
        super();
    }

        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        @DynamoDBAttribute
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @DynamoDBAttribute
        public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @JsonProperty("cedula")
    @DynamoDBAttribute(attributeName = "cedula")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "cedula-index")
    public int getCedula() {
        return cedula;
    }

    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
}